server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/auth/ {
        proxy_pass ${MS_AUTH_URL}/api/auth/;
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
        proxy_ssl_verify off;
    }
    location /api/usuarios/ {
        proxy_pass ${MS_USUARIOS_URL}/api/usuarios/;
        proxy_set_header Host $proxy_host;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
        proxy_ssl_verify off;
    }
    location /api/recursos/ {
        proxy_pass ${MS_RECURSOS_URL}/api/recursos/;
        proxy_set_header Host $proxy_host;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
        proxy_ssl_verify off;
        client_max_body_size 55M;
    }
    location /api/valoraciones/ {
        proxy_pass ${MS_VALORACIONES_URL}/api/valoraciones/;
        proxy_set_header Host $proxy_host;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
        proxy_ssl_verify off;
    }
    location /api/descargas/ {
        proxy_pass ${MS_DESCARGAS_URL}/api/descargas/;
        proxy_set_header Host $proxy_host;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
        proxy_ssl_verify off;
    }
    location /api/reportes/ {
        proxy_pass ${MS_REPORTES_URL}/api/reportes/;
        proxy_set_header Host $proxy_host;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
        proxy_ssl_verify off;
    }
    location /api/notificaciones/ {
        proxy_pass ${MS_NOTIFICACIONES_URL}/api/notificaciones/;
        proxy_set_header Host $proxy_host;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
        proxy_ssl_verify off;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript;

    location ~* \.(js|css|png|ico|svg|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
